# Export SNOWFLAKE_PRIVATE_KEY_PATH and SNOWFLAKE_DATABASE as environment variables
# or set them in the profiles.yml file

medallion_reference:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      authenticator: SNOWFLAKE_JWT
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads: 4

    duckdb:
      type: duckdb
      path: ./medallion-reference.duckdb
      schema: main
      threads: 4
